Função que retorna a solução de um sistema linear de equações usando o método Eliminação de Gauss

In [75]:
import numpy as np

In [77]:
#Coeficientes
A = np.array([[4,3,2], [-2,2,3], [3,-5,2]])
A  

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [79]:
#Constantes
B = np.array([25,-10,-4])
B

array([ 25, -10,  -4])

In [99]:
def gauss_elimination(M1,M2):

    #Calculo linha 2 em x
    pivot1 = M1[1][0]/M1[0][0]
    M2[1] = M2[1] - M2[0]*pivot1
    for j in range(M1.shape[1]):
        M1[1][j] = M1[1][j] - M1[0][j]*pivot1
        
    #calculo linha 3 em x    
    pivot2 = M1[2][0]/M1[0][0]
    M2[2] = M2[2] - M2[0]*pivot2
    for j in range(M1.shape[1]):
        M1[2][j] = M1[2][j] - M1[0][j]*pivot2
    print(M1,M2)

    #calculo linha 3 em y; usando para calculo do pivot a linha 2;
    pivot3 = M1[2][1]/M1[1][1]
    M2[2] = M2[2] - M2[1]*pivot3
    for j in range(M1.shape[1]):
        M1[2][j] = M1[2][j] - M1[1][j]*pivot3
    print(M1,M2)
       
    z = M2[2]/M1[2][2]
    y = (M2[1] - M1[1][2]*z)/M1[1][1]
    x = (M2[0] - M1[0][2]*z - M1[0][1]*y)/M1[0][0]

    print("x = {}, y = {}, z = {}".format(x,y,z))
    
    return np.array([x,y,z])                 

In [101]:
gauss_elimination(A,B)

[[4 3 2]
 [0 3 4]
 [0 0 9]] [ 25   2 -17]
[[4 3 2]
 [0 3 4]
 [0 0 9]] [ 25   2 -17]
x = 4.805555555555555, y = 3.185185185185185, z = -1.8888888888888888


array([ 4.80555556,  3.18518519, -1.88888889])

In [85]:
result = np.linalg.solve(A,B)
result

array([ 4.80555556,  3.18518519, -1.88888889])