In [ ]:
#Coding a function that takes a square matrix of any order and returns its determinant

In [1]:
import numpy as np

In [3]:
M2 = np.random.randint(10, size=(2,2))
M2

array([[4, 0],
       [4, 5]])

In [5]:
M3 = np.random.randint(10, size=(3,3))
M3

array([[8, 9, 9],
       [5, 3, 6],
       [7, 1, 8]])

In [40]:
M4 = np.random.randint(10, size=(4,4))
M4

array([[9, 2, 4, 4],
       [9, 9, 1, 4],
       [2, 0, 8, 6],
       [6, 3, 3, 1]])

In [42]:
M5 = np.random.randint(10, size=(5,5))
M5


array([[1, 4, 4, 1, 9],
       [9, 4, 1, 3, 0],
       [8, 2, 5, 3, 7],
       [2, 6, 7, 0, 3],
       [9, 7, 2, 6, 2]])

In [44]:
#Matriz é uma matriz quadrada ?
def matriz_quadrada(matriz):
    return(matriz.shape[0]== matriz.shape[1])

In [46]:
def minor(matriz, row, col):
    #Deleta a linha "i" da matriz conforme entrada na função determinante e armazena resultada na minor_matriz 
    minor_matriz = np.delete(matriz, row, 0)
    #print(matriz, minor_matriz)
        
    #Remove a coluna "J" conforme entrada na função determinante
    minor_matriz = np.delete(minor_matriz, col, 1)
        
    #print("Matriz Minor:")
    #print(minor_matriz)
        
    #retorna matriz minor
    return minor_matriz

def determinante(matriz):
    
    if matriz_quadrada(matriz):
        (row,col) = matriz.shape
        
        # Determinante Matriz quadrada 2x2 -> produto das diagonais
        if (row, col) == (2, 2):
            return matriz[0][0] * matriz[1][1] - matriz[0][1] * matriz[1][0]
            
         # Determinante Matriz quadrada 3 x 3 Regra de Sarrus    
        elif (row, col) == (3, 3):
            return (((matriz[0][0]*matriz[1][1]*matriz[2][2]) 
                     + (matriz[0][1]*matriz[1][2]*matriz[2][0]) 
                     + (matriz[0][2]*matriz[1][0]*matriz[2][1]))
                     -((matriz[0][2]*matriz[1][1]*matriz[2][0])
                      + (matriz[0][0]*matriz[1][2]*matriz[2][1])
                      + (matriz[0][1]*matriz[1][0]*matriz[2][2])))
            
        #Determinante Matriz quadrada >= 4x4 usando expansão de Laplace
        elif (row, col) >= (4,4):
            det = 0
            #Encontrar menor elemento da Matriz
            min_element = np.argmin(matriz)
            #Retorna o indice (linha, coluna) do menor elemento
            (i_min, j_min) = np.unravel_index(min_element, matriz.shape)
            
            for j in range(len(matriz)):
                #usa a linha do menor elemento para determinar matriz minor
                cofactor = ((-1)**(i_min +j)) * determinante(minor(matriz, i_min, j))
                
                #multiplicação do elemento[i_min][j] da matriz inicial pelo seu cofator
                det += matriz[i_min][j] * cofactor
            return det
    return "A matriz não é quadrada"                                 

In [48]:
## Determinante Matriz 2x2
print("Determinante Matriz Quadrada 2x2 produto das diagonais:", determinante(M2))
print("Determinante Matriz Quadrada 2x2 usando linalg:", round(np.linalg.det(M2)))

Determinante Matriz Quadrada 2x2 produto das diagonais: 20
Determinante Matriz Quadrada 2x2 usando linalg: 20


In [50]:
## Determinante Matriz 3x3
print("Determinante Matriz Quadrada 3x3 Regra de Sarrus:", determinante(M3))
print("Determinante Matriz Quadrada 3x3 usando linalg:", round(np.linalg.det(M3)))

Determinante Matriz Quadrada 3x3 Regra de Sarrus: 18
Determinante Matriz Quadrada 3x3 usando linalg: 18


In [52]:
#Determinante Matriz 4x4
print("Determinante Matriz Quadrada 4x4 Laplace:", determinante(M4))
print("Determinante Matriz Quadrada 4x4 usando linalg:", round(np.linalg.det(M4)))

Determinante Matriz Quadrada 4x4 Laplace: -1064
Determinante Matriz Quadrada 4x4 usando linalg: -1064


In [54]:
#Determinante Matrix 5x5
print("Determinante Matriz Quadrada 5x5 Laplace:", determinante(M5))
print("Determinante Matriz Quadrada 5x5 usando linalg:", round(np.linalg.det(M5)))

Determinante Matriz Quadrada 5x5 Laplace: -6498
Determinante Matriz Quadrada 5x5 usando linalg: -6498
