In [1]:
# Funçao Multiplição 
# 1 checar se essas matrizes são multiplicaveis 
# Checar se o número de colunas de A é igual ao número de linhas de B 
# Criar um matriz com zeros usando o número de linhas de A x Numero de colunas de B
# Comparar resultados com a biblioteca A@B

In [2]:
import numpy as np

In [3]:
# Matriz A 2x3
A = np.random.randint(10, size=(4,5))
print("Matriz A:\n", A)

Matriz A:
 [[7 2 4]
 [8 7 2]
 [9 6 5]]


In [17]:
B = np.random.randint(10, size=(3,5))
print("Matriz B:\n", B)

Matriz B:
 [[3 7 2 6 0]
 [8 5 3 2 0]
 [6 2 7 4 8]]


In [18]:
#Multiplicação entre as matrizes é valida A(NxM) B(KxJ): M = K ?
def mult_is_valid(M1, M2):
    return(M1.shape[1]== M2.shape[0])

In [19]:
mult_is_valid(A,B)

True

In [20]:
# Element perspective
def matmul_element(M1,M2):
    if mult_is_valid(M1,M2):
        #criar matriz de zeros (NxJ)
        M3= np.zeros((M1.shape[0],M2.shape[1]))
        #iteração i = linhas M1
        for i in range(M1.shape[0]):
            # iteração j = colunas M2
            for j in range(M2.shape[1]):
                # Cada elemento da M3[i,j] recebe o produto escalar do vetor linha i de M1 e da coluna j M2
                M3[i,j] = np.dot(M1[i,:], M2[:,j])
        return M3
    return 'A multiplicação não é valida'

In [21]:
# layer perspective
def matmul_layer(M1,M2):
    #validar multiplicação de matriz
    if mult_is_valid(M1,M2):    
        #criar matriz de zeros (NxJ)
        M3=np.zeros((M1.shape[0],M2.shape[1]))
        #iteração na coluna i na matriz M1
        for i in range(M1.shape[1]):
            #função outer multiplica a coluna inteira [:,i] com a linha inteira [i,:] da M2
            layer = np.outer(M1[:,i], M2[i,:]) 
            # Valor é acumulado na M3, 
            # que nas próximas iterações irá somar a nova camada as demais camadas ja criadas
            M3 += layer
        return M3    
    return 'A multiplicação não é valida'

In [22]:
#column perspective
def matmul_column(M1,M2):
    #validar multiplicação de matriz
    if mult_is_valid(M1,M2):    
        #criar matriz de zeros (NxJ)
        M3=np.zeros((M1.shape[0],M2.shape[1]))
        #iteração nas colunas na matriz M2, número de iterações conforme o número de colunas de M2
        for j in range(M2.shape[1]):
            #iteração nas colunas da matriz M1,
            for i in range(M1.shape[1]):
                #coluna é resultado da multiplicaçao da coluna i de M1 com o elemento ij de M2
                #O elemento j em M2[i,j] se mantem constante e iteramos o i para pegar elemento a elemento da linha j de M2
                #Número de colunas de M3 deve ser igual ao M2
                M3[:,j] += M1[:,i]*M2[i,j]
        return M3    
    return 'A multiplicação não é valida'

In [23]:
#Row perspective
def matmul_row(M1,M2):
    #validar multiplicação de matriz
    if mult_is_valid(M1,M2):    
        #criar matriz de zeros (NxJ)
        M3=np.zeros((M1.shape[0],M2.shape[1]))
        #iteração nas linhas na matriz M1, número de iterações conforme o número de linhas de M1
        for i in range(M1.shape[0]):
            #iteração nas linhas da matriz M2, pegando elemento a elemento de M1 utilizando como parametro fixo i
            for j in range(M2.shape[0]):
                #O número de linhas da M3 deve ser igual ao M1
                #Linha de M3 é resultado da multiplicaçao do elemento M1[i,j] pela linha inteira j de M2
                #Na M1 utilizando i como parametro constante e iteramos o j para pegar elemento a elemento da linha i de M1
                M3[i,:] += M1[i,j]*M2[j,:]
        return M3    
    return 'A multiplicação não é valida'

In [24]:
def check_multi_func(M1, M2):
    
    # funçao multi_elemento
    M_element = matmul_element(M1, M2)
    M_layer = matmul_layer(M1,M2)
    M_column= matmul_column(M1,M2)
    M_row = matmul_row(M1,M2)
    
    # Calculo usando numpy multiplicação matriz 
    M_np = M1@M2
    
    if (np.allclose(M_element, M_np) and 
        np.allclose(M_layer, M_np) and 
        np.allclose(M_column, M_np) and 
        np.allclose(M_row, M_np)):
        return print('Matriz de multiplicação iguais ao M1@M2')
       
    else:
        return print('As matrizes não são iguais ao M1@M2')

In [25]:
check_multi_func(A,B)

Matriz de multiplicação iguais ao M1@M2


In [27]:
print("---------------")
print("Multiplicação elementos: ")
print(matmul_element(A,B))
print("---------------")
print("Multiplicação camadas: ")
print(matmul_layer(A,B))
print("---------------")
print("Multiplicação colunas: ")
print(matmul_column(A,B))
print("---------------")
print("Multiplicação linhas: ")
print(matmul_row(A,B))
print("---------------")
print("Multiplicação usando numpy @:")
print(matmul_row(A,B))

---------------
Multiplicação elementos: 
[[ 61.  67.  48.  62.  32.]
 [ 92.  95.  51.  70.  16.]
 [105. 103.  71.  86.  40.]]
---------------
Multiplicação camadas: 
[[ 61.  67.  48.  62.  32.]
 [ 92.  95.  51.  70.  16.]
 [105. 103.  71.  86.  40.]]
---------------
Multiplicação colunas: 
[[ 61.  67.  48.  62.  32.]
 [ 92.  95.  51.  70.  16.]
 [105. 103.  71.  86.  40.]]
---------------
Multiplicação linhas: 
[[ 61.  67.  48.  62.  32.]
 [ 92.  95.  51.  70.  16.]
 [105. 103.  71.  86.  40.]]
---------------
Multiplicação usando numpy @:
[[ 61.  67.  48.  62.  32.]
 [ 92.  95.  51.  70.  16.]
 [105. 103.  71.  86.  40.]]
