In [21]:
import numpy as np
import matplotlib.pyplot as plt

#Generate a vector A with 100 random real numbers between 0 and 100
rng = np.random.default_rng(seed = 1)
A = np.round(rng.random(100) + rng.integers(0,100,100), 2)
A

array([50.51, 65.95, 15.14, 43.95, 88.31, 86.42, 31.83, 63.41,  8.55,
       81.03, 26.75, 34.54, 96.33, 54.79, 87.3 , 19.45, 75.13, 99.4 ,
        7.2 , 24.26, 14.75, 25.28, 31.49,  7.98, 89.96, 25.72, 92.54,
       76.28, 17.16, 69.97, 77.52, 12.12, 12.62, 37.78,  6.61, 42.92,
       47.04, 66.53, 57.46, 45.06, 22.64, 58.85, 45.59, 83.26, 69.84,
       72.51, 57.51, 36.75, 28.15, 44.82, 57.68, 36.79, 14.19, 10.8 ,
        4.19, 20.08, 40.86, 28.86, 17.88, 31.47, 71.27, 31.01, 91.65,
       57.72, 13.84, 97.28, 88.22, 77.64, 15.81, 79.96, 70.15, 75.48,
       71.89, 59.42, 34.59, 91.02, 98.67, 68.92, 35.83, 50.89, 56.66,
        7.25,  8.77, 48.21, 56.83, 21.06, 26.83, 13.16, 91.38, 50.32,
       27.69, 78.18, 95.4 , 29.01, 89.26, 76.42, 79.11, 52.63, 91.38,
       14.73])

In [22]:
#Generate a vector B with 100 random real numbers between 0 and 1
B = np.round(rng.random(100),2) 
B

array([0.96, 0.4 , 0.3 , 0.85, 0.12, 0.73, 0.19, 0.39, 0.23, 0.84, 0.39,
       0.97, 0.63, 0.69, 0.52, 0.31, 0.4 , 0.94, 0.2 , 0.99, 0.76, 0.36,
       0.64, 0.38, 0.38, 0.5 , 0.02, 0.49, 0.97, 0.29, 0.75, 0.44, 0.21,
       0.91, 0.02, 0.3 , 1.  , 0.26, 0.85, 0.61, 0.81, 0.63, 0.36, 0.76,
       0.03, 0.45, 0.37, 0.48, 0.13, 0.22, 0.56, 0.39, 0.79, 0.61, 0.86,
       0.73, 0.6 , 0.29, 0.78, 0.25, 0.08, 0.96, 0.54, 0.77, 0.53, 0.61,
       0.03, 0.19, 0.67, 0.57, 0.16, 0.95, 0.15, 0.51, 0.14, 0.72, 0.28,
       0.13, 0.05, 0.17, 0.19, 0.54, 0.45, 0.96, 0.95, 0.8 , 0.67, 0.85,
       0.94, 0.02, 0.12, 0.36, 0.09, 0.6 , 0.26, 0.26, 0.29, 0.1 , 0.74,
       0.65])

In [23]:
#Rescale both vectors so that they have values between 5 and 10 using your own function

def rescale_linear(array, new_min, new_max):
    maximum, minimum = np.max(array), np.min(array)
    normalized = (array - minimum)/(maximum - minimum) 
    b = new_max - new_min
    return new_min + normalized * b
vA_minmax = np.round(rescale_linear(A , 5, 10),2)
vA_minmax

array([ 7.43,  8.24,  5.58,  7.09,  9.42,  9.32,  6.45,  8.11,  5.23,
        9.04,  6.18,  6.59,  9.84,  7.66,  9.36,  5.8 ,  8.73, 10.  ,
        5.16,  6.05,  5.55,  6.11,  6.43,  5.2 ,  9.5 ,  6.13,  9.64,
        8.79,  5.68,  8.45,  8.85,  5.42,  5.44,  6.76,  5.13,  7.03,
        7.25,  8.27,  7.8 ,  7.15,  5.97,  7.87,  7.17,  9.15,  8.45,
        8.59,  7.8 ,  6.71,  6.26,  7.13,  7.81,  6.71,  5.53,  5.35,
        5.  ,  5.83,  6.93,  6.3 ,  5.72,  6.43,  8.52,  6.41,  9.59,
        7.81,  5.51,  9.89,  9.41,  8.86,  5.61,  8.98,  8.46,  8.74,
        8.56,  7.9 ,  6.6 ,  9.56,  9.96,  8.4 ,  6.66,  7.45,  7.76,
        5.16,  5.24,  7.31,  7.76,  5.89,  6.19,  5.47,  9.58,  7.42,
        6.23,  8.89,  9.79,  6.3 ,  9.47,  8.79,  8.93,  7.54,  9.58,
        5.55])

In [24]:
vB_minmax = np.round(rescale_linear(B , 5, 10),2)
vB_minmax

array([ 9.8 ,  6.94,  6.43,  9.23,  5.51,  8.62,  5.87,  6.89,  6.07,
        9.18,  6.89,  9.85,  8.11,  8.42,  7.55,  6.48,  6.94,  9.69,
        5.92,  9.95,  8.78,  6.73,  8.16,  6.84,  6.84,  7.45,  5.  ,
        7.4 ,  9.85,  6.38,  8.72,  7.14,  5.97,  9.54,  5.  ,  6.43,
       10.  ,  6.22,  9.23,  8.01,  9.03,  8.11,  6.73,  8.78,  5.05,
        7.19,  6.79,  7.35,  5.56,  6.02,  7.76,  6.89,  8.93,  8.01,
        9.29,  8.62,  7.96,  6.38,  8.88,  6.17,  5.31,  9.8 ,  7.65,
        8.83,  7.6 ,  8.01,  5.05,  5.87,  8.32,  7.81,  5.71,  9.74,
        5.66,  7.5 ,  5.61,  8.57,  6.33,  5.56,  5.15,  5.77,  5.87,
        7.65,  7.19,  9.8 ,  9.74,  8.98,  8.32,  9.23,  9.69,  5.  ,
        5.51,  6.73,  5.36,  7.96,  6.22,  6.22,  6.38,  5.41,  8.67,
        8.21])

In [44]:
#Compute the Pearson Correlation Coefficient between the rescaled vectors A and B using 
# only the basic operators provided by the NumPy
media_A = np.sum(vA_minmax)/ len(vA_minmax)
media_B = np.sum(vB_minmax) / len(vB_minmax)

r = np.round(np.sum((vA_minmax - media_A)*(vB_minmax - media_B))/np.sqrt(np.sum((vA_minmax - media_A)**2)*np.sum((vB_minmax - media_B)**2)), 5)
r

-0.0989

In [45]:
from scipy.stats import pearsonr
corr, _ = np.round(pearsonr(vA_minmax, vB_minmax),5)
corr

-0.0989

In [46]:
# Nesse exemplo, não houve diferença entre as correlações calculadas pelo metodo da biblioteca scipy.stats e o usando operações básicas
diff = corr - r
diff

0.0

In [47]:
#Verify if the correlation is different when considering the original vectors without rescaling
media_A = np.sum(A)/len(A)
media_B = np.sum(B)/len(B)
r = np.round(np.sum((A - media_A)*(B - media_B))/np.sqrt(np.sum((A - media_A)**2)*np.sum((B - media_B)**2)),5)
r

-0.09857

In [48]:
from scipy.stats import pearsonr
corr, _ = np.round(pearsonr(A, B),5)
corr

-0.09857

In [49]:
diff = corr - r
diff

0.0

In [ ]:
#A correlação dos vetores se mantem similar quando usando os vetores orignais. 
# O que é esperando, já que a reescala do vetor não deve mudar seu comportamento original, apenas trata os dados para que sua magnetude fique dentro de um range predeterminado.
# Portanto a reescalava não deve mudar a correlação de pearson entre os dois vetores, que nesse caso se manteve "Strongly negative" 